network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: no
      addresses:
        - 192.168.178.155/24
      gateway4: 192.168.178.1
      nameservers:
          addresses: [192.168.178.1]