---

- hosts: all
  become: true
  tags: always
  roles:
    - base
  vars_files:
    - defaults/main.yml

- hosts: server
  become: true
  tags: server
  roles:
    - server
  vars_files:
    - defaults/main.yml

- hosts: workstation
  become: true
  tags: workstation
  roles:
    - workstation
  vars_files:
    - defaults/main.yml

- hosts: arch_linux_install
  become: true
  tags: arch_linux_install
  roles:
    - arch_linux_install
  vars_files:
    - defaults/main.yml
    - host_vars/passwords.yml

- hosts: nextcloud_install
  become: true
  tags: nextcloud_install
  roles:
    - server
    - nextcloud_install
  vars_files:
    - defaults/main.yml
    - host_vars/passwords.yml

- hosts: localhost
  connection: local
  become: true
  tags: control_host
  roles:
    - base
    - server
  vars_files:
    - defaults/main.yml
