---

- hosts: all
  become: true
  tags: base
  roles:
    - base

- hosts: server
  become: true
  tags: server
  roles:
    - server

- hosts: workstation
  become: true
  tags: workstation
  roles:
    - workstation

- hosts: arch_linux_install
  become: true
  tags: arch_linux_install
  roles:
    - arch_linux_install
