---

- hosts: all
  become: true
  roles:
    - base

- hosts: server
  become: true
  tags: server
  roles:
    - server

- hosts: workstation
  become: true
  tags: workstation
  roles:
    - workstation

- hosts: arch_linux_install
  become: true
  tags: arch_linux_install
  roles:
    - arch_linux_install

- hosts: proxmox_install
  become: true
  tags: proxmox_install
  roles:
    - server
    - proxmox_install

- hosts: nextcloud_install
  become: true
  tags: nextcloud_install
  roles:
    - server
    - nextcloud_install
