- name: install apache2
  package:
    name: apache2
    state: latest

- name: start apache2
  systemd:
    name: apache2
    state: started

- name: enable apache2
  systemd:
    name: apache2
    enabled: true

- name: install required php packages
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - libapache2-mod-php{{ php_version }}
    - php{{ php_version }}-gd
    - php{{ php_version }}-mysql
    - php{{ php_version }}-curl
    - php{{ php_version }}-mbstring
    - php{{ php_version }}-intl
    - php{{ php_version }}-gmp
    - php{{ php_version }}-bcmath
    - php{{ php_version }}-xml
    - php{{ php_version }}-zip
    - php-imagick
    - php-apcu

- name: enable php mods
  command: phpenmod bcmath gmp imagick intl

- name: download nextcloud from source and put it into /var/www/ directory
  get_url:
    url: https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_version }}.zip
    dest: /var/www/

- name: install unzip
  package:
    name: unzip
    state: latest

- name: unzip nextcloud download
  unarchive:
    src: /var/www/nextcloud-{{ nextcloud_version }}.zip
    dest: /var/www/
    remote_src: true

- name: rename nextcloud root directory to {{ nextcloud_domain_name }}
  command: mv /var/www/nextcloud /var/www/{{ nextcloud_domain_name }}

- name: remove zip archive
  file:
    path: /var/www/nextcloud-{{ nextcloud_version }}.zip
    state: absent

- name: change owner and group of /var/www/{{ nextcloud_domain_name }}
  file:
    path: /var/www/{{ nextcloud_domain_name }}
    owner: www-data
    group: www-data
    recurse: true

- name: disable apache default website
  command: a2dissite 000-default.conf

- name: create apache config file for nextcloud site
  template:
    src: apache/nextcloud.conf.j2
    dest: /etc/apache2/sites-available/{{ nextcloud_domain_name }}.conf

- name: enable newly created config file
  command: a2ensite {{ nextcloud_domain_name }}

- name: enable required apache mods
  command: a2enmod dir env headers mime rewrite ssl

- name: adjust nextcloud config.ini configuration
  lineinfile:
    path: /etc/php/{{ php_version }}/apache2/php.ini
    regexp: '^memory_limit(.*)$'
    line: memory_limit = 512M

- name: install certbot and python certbot apache
  package:
    name: '{{ item }}'
    state: latest
  loop:
    - certbot
    - python3-certbot-apache

- name: obtain ssl certificate
  command: certbot --apache --domain {{ nextcloud_domain_name }} --redirect --agree-tos --register-unsafely-without-email

- name: allow port 80
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: allow port 443
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: restart apache service to apply changes
  systemd:
    name: apache2
    state: restarted
