- name: install snap
  apt:
    name: snapd
    state: latest

- name: install nextcloud from snap
  snap:
    name: nextcloud
    state: present

- name: install nextcloud
  command: /snap/bin/nextcloud.manual-install root test
