- name: remove unnecessary apps
  command: /snap/bin/nextcloud.occ app:disable "{{ item }}"
  loop:
    - dashboard
    - activity
    - photos

- name: enable two factor authentication
  command: /snap/bin/nextcloud.occ app:enable twofactor_totp
