- name: clone AUR packages
  git:
    repo: '{{ item.url }}'
    dest: '{{ item.dest }}'
  loop:
    - {url: https://aur.archlinux.org/spotify.git, dest: /opt/spotify/}
    - {url: https://aur.archlinux.org/downgrade.git, dest: /opt/downgrade/}
    - {url: https://aur.archlinux.org/virtualbox-ext-oracle.git, dest: /opt/virtualbox-ext-oracle}
    - {url: https://github.com/ventoy/Ventoy.git, dest: /opt/ventoy/}           # added although it's technically not an aur package

- name: change ownership of package directory temporarily to ansible
  file:
    path: '{{ item }}'
    owner: ansible
    group: ansible
    state: directory
    recurse: true
  loop:
    - /opt/spotify
    - /opt/downgrade
    - /opt/virtualbox-ext-oracle

- name: build and install
  become_user: ansible
  shell: "/usr/bin/makepkg -si --noconfirm --skipinteg"
  args:
    chdir: '{{ item }}'
  loop:
    - /opt/spotify
    - /opt/downgrade
    - /opt/virtualbox-ext-oracle

- name: change ownership of package directory permanently to jogi
  file:
    path: '{{ item }}'
    owner: jogi
    group: jogi
    state: directory
    recurse: true
  loop:
    - /opt/spotify
    - /opt/downgrade
    - /opt/virtualbox-ext-oracle
