- name: install bluetooth driver
  package:
    name: bluez
    state: latest

- name: install pulseaudio bluetooth support for Debian-based systems
  package:
    name: pulseaudio-module-bluetooth
    state: latest

- name: install pulseaudio bluetooth support for Arch-based systems
  package:
    name: pulseaudio-bluetooth
    state: latest

- name: install kde bluetooth applet
  package:
    name: bluedevil
    state: latest

- name: start and enable bluetooth service
  systemd:
    name: bluetooth
    state: started
    enabled: true
