- name: install flatpak
  package:
    name: flatpak
    state: latest

- name: add official flathub repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: install flatpak packages
  flatpak:
    name:
      - com.spotify.Client
      - org.onlyoffice.desktopeditors
    state: present
