- name: install nvidia drivers and tools
  package:
    name: '{{ item }}'
  loop:
    - nvidia
    - nvidia-lts
    - nvidia-utils
    - nvidia-settings
    - nvidia-prime
  when: primary_gpu is defined and primary_gpu == 'nvidia'

- name: install intel integrated gpu driver
  package:
    name: xf86-video-intel
    state: latest
  when: integrated_gpu is defined and integrated_gpu == 'intel'
