- name: install nvidia drivers and tools
  package:
    name: '{{ item }}'
  loop:
    - nvidia
    - nvidia-lts
    - nvidia-utils
    - nvidia-settings
    - nvidia-prime

- name: install intel integrated gpu driver
  package:
    name: xf86-video-intel
    state: latest
  when: has_intel_integrated_gpu is defined and has_intel_integrated_gpu == true
