- name: add latte dock to KDE autostart menu
  copy:
    src: /usr/share/applications/org.kde.latte-dock.desktop
    dest: /home/jogi/.config/autostart/org.kde.latte-dock.desktop
    remote_src: true

- name: add yakuake to KDE autostart menu
  copy:
    src: /usr/share/applications/org.kde.yakuake.desktop
    dest: /home/jogi/.config/autostart/org.kde.yakuake.desktop
    remote_src: true
