- name: include workstation tasks
  include_tasks: "{{ item }}"
  loop:
    #- zsh_installation.yml
    #- audio_setup.yml
    #- bluetooth_setup.yml
    #- nfs_client_setup.yml
    #- gpu_drivers_setup.yml
    #- kde_plasma_setup.yml
    #- sddm_configuration.yml
    #- packages.yml
    #- printer_setup.yml
    #- aur_packages.yml
    #- pentesting_setup.yml
    #- grub_configuration.yml
