- name: include workstation tasks
  include_tasks: "{{ item }}"
  loop:
    #- gpu_drivers_setup.yml
    #- kde_plasma_setup.yml
    #- sddm_configuration.yml
    #- bluetooth_setup.yml
    #- audio_setup.yml
    #- printer_setup.yml
    #- packages.yml
    #- zsh_installation.yml
    #- pentesting_setup.yml

- include_tasks: aur_packages.yml
  when: ansible_distribution == 'Archlinux'

- include_tasks: energy_saving.yml
  when: is_laptop is defined and is_laptop == true

- name: include other workstation tasks
  include_tasks: '{{ item }}'
  loop:
    #- nfs_client_setup.yml
    #- grub_configuration.yml
