- name: include workstation tasks
  include_tasks: "{{ item }}"
  loop:
    - gpu_drivers_setup.yml
    - kde_plasma_setup.yml
    - sddm_configuration.yml
    - audio_setup.yml
    - printer_setup.yml
    - packages.yml
    - zsh_installation.yml
    - pentesting_setup.yml
    - flatpak_installation.yml

- include_tasks: bluetooth_setup.yml
  when: bluetooth is defined and bluetooth == true

- include_tasks: aur_packages.yml
  when: ansible_os_family == 'Archlinux'

- include_tasks: energy_saving.yml
  when: laptop is defined and laptop == true

- name: include other workstation tasks
  include_tasks: '{{ item }}'
  loop:
    - nfs_client_setup.yml
    - grub_configuration.yml
