- name: install nfs client on Debian-based systems
  package:
    name: nfs-common
    state: latest

- name: install nfs package on Arch-based systems
  package:
    name: nfs-utils
    state: latest

- name: install autofs
  package:
    name: autofs
    state: latest

- name: start and enable autofs
  systemd:
    name: autofs
    state: started
    enabled: true

- name: copy auto.master from template
  template:
    src: autofs/auto.master.j2
    dest: /etc/autofs/auto.master

- name: copy auto.truenas from template
  template:
    src: autofs/auto.truenas.j2
    dest: /etc/autofs/auto.truenas
