- name: install nfs client on Debian-based systems
  package:
    name: nfs-common
    state: latest
  when: ansible_os_family == 'Debian'

- name: install nfs package on Arch-based systems
  package:
    name: nfs-utils
    state: latest
  when: ansible_os_family == 'Archlinux'
