- name: install pacman packages
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - ansible
    - bash-completion
    - curl
    - exfat-utils
    - flatpak
    - git
    - nano
    - nfs-utils
    - nmap
    - openssh
    - openvpn
    - rsync
    - tlp
    - wget
    - vim
    - zsh

    #desktop apps
    - arduino
    - arduino-avr-core
    - firefox
    - keepassxc
    - pycharm-community-edition
    - torbrower-launcher
    - wireshark
    - vlc
