- name: install packages
  package:
    name: "{{ item }}"
    state: latest
  loop:
    # terminal utils
    - speedtest-cli
    - nmap
    - openvpn
    # development utils
    - ansible
    - openscad
    - virtualbox
    - pycharm-community-edition
    - arduino
    - arduino-avr-core
    - wireshark
    # desktop utils
    - konsole
    - firefox
    - vlc
    - gwenview
    - spectacle
    - filelight
    - keepassxc
    - kate
    - partitionmanager
    - torbrower-launcher
    - geogebra
