- name: install pacman packages
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - ansible
    - bash-completion
    - curl
    - exfat-utils
    - flatpak
    - git
    - nano
    - nfs-utils
    - nmap
    - openssh
    - openvpn
    - rsync
    - tlp
    - wget
    - vim
    - zsh

    #desktop apps
    - arduino
    - arduino-avr-core
    - firefox
    - keepassxc
    - pycharm-community-edition
    - torbrower-launcher
    - wireshark
    - vlc

- name: flatpak add flathub repo
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: install flatpak packages
  flatpak:
    name: "{{ item }}"
    state: present
  loop:
    - com.spotify.Client
    - org.onlyoffice.desktopeditors
