- name: install packages
  package:
    name: "{{ item }}"
    state: latest
  loop:
    # terminal utils
    - nvidia-smi
    - speedtest-cli
    - nmap
    # development utils
    - ansible
    - openscad
    - virtualbox
    - pycharm-community-edition
    - arduino
    - arduino-avr-core
    - kdevelop
    - wireshark
    - gparted
    # desktop utils
    - firefox
    - vlc
    - gwenview
    - spectacle
    - filelight
    - keepassxc
    - kate
