- name: create sddm.conf.d directory
  file:
    path: /etc/sddm.conf.d/
    state: directory

- name: make breeze theme the default for sddm
  template:
    src: sddm/theme.conf.j2
    dest: /etc/sddm.conf.d/theme.conf
