- name: install zsh
  package:
    name: zsh
    state: latest

- name: create zsh-themes directory
  file:
    path: /home/jogi/.zsh-themes
    state: directory

- name: create gnzh directory inside .zsh-themes
  file:
    path: /home/jogi/.zsh-themes/gnzh
    state: directory

- name: load gnzh theme from template
  template:
    src: zsh/gnzh.zsh-theme.j2
    dest: /home/jogi/.zsh-themes/gnzh/gnzh.zsh-theme


- name: install zsh-autosuggestions
  package:
    name: zsh-autosuggestions
    state: latest

- name: install zsh-completions
  package:
    name: zsh-completions
    state: latest

- name: install zsh-syntax-highlighting
  package:
    name: zsh-syntax-highlighting
    state: latest

- name: create .zshrc from template
  template:
    src: zsh/.zshrc.j2
    dest: /home/jogi/.zshrc

- name: change ownership of .zsh-themes directory to jogi
  file:
    path: /home/jogi/.zsh-themes/
    owner: jogi
    group: jogi
    mode: '0755'
    state: directory
    recurse: yes

- name: change ownership of .zshrc to jogi
  file:
    path: /home/jogi/.zshrc
    owner: jogi
    group: jogi
    mode: '0755'

- name: make zsh the default shell
  user:
    name: jogi
    shell: /usr/bin/zsh
