- name: install zsh
  package:
    name: zsh
    state: latest

- name: create zsh-themes directory
  file:
    path: /home/jogi/.zsh-themes
    state: directory

- name: create gnzh directory inside .zsh-themes
  file:
    path: /home/jogi/.zsh-themes/gnzh
    state: directory

- name: load gnzh theme from template
  template:
    src: zsh/gnzh.zsh-theme.j2
    dest: /home/jogi/.zsh-themes/gnzh/gnzh.zsh-theme


- name: create zsh-plugins directory
  file:
    path: /home/jogi/.zsh-plugins
    state: directory

- name: create zsh-autosuggestions directory
  file:
    path: /home/jogi/.zsh-plugins/zsh-autosuggestions/
    state: directory

- name: download zsh autosuggestions plugin
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: /home/jogi/.zsh-plugins/zsh-autosuggestions

- name: download zsh completion plugin
  git:
    repo: https://github.com/zsh-users/zsh-completions.git
    dest: /home/jogi/.zsh-plugins/zsh-completions/

- name: download zsh-syntax-highlighting plugin
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /home/jogi/.zsh-plugins/zsh-syntax-highlighting

- name: create .zshrc from template
  template:
    src: zsh/.zshrc.j2
    dest: /home/jogi/.zshrc

- name: change ownership of created directories to jogi
  file:
    path: '{{ item }}'
    owner: jogi
    group: jogi
    mode: '0755'
    state: directory
    recurse: yes
  loop:
    - /home/jogi/.zsh-plugins/
    - /home/jogi/.zsh-themes/

- name: change ownership of .zshrc to jogi
  file:
    path: /home/jogi/.zshrc
    owner: jogi
    group: jogi
    mode: '0755'

- name: make zsh the default shell
  user:
    name: jogi
    shell: /usr/bin/zsh