- name: install zsh
  package:
    name: zsh
    state: latest

- name: create zsh-themes directory
  file:
    path: /home/jogi/.zsh-themes
    state: directory
    mode: '0755'

- name: create gnzh directory inside .zsh-themes
  file:
    path: /home/jogi/.zsh-themes/gnzh
    state: directory
    mode: '0755'

- name: download gnzh theme
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/themes/gnzh.zsh-theme
    dest: /home/jogi/.zsh-themes/gnzh/


- name: create zsh-plugins directory
  file:
    path: /home/jogi/.zsh-plugins
    state: directory
    mode: '0755'

- name: download zsh autosuggestions plugin
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: /home/jogi/.zsh-plugins/

- name: download zsh completion plugin
  git:
    repo: https://github.com/zsh-users/zsh-completions.git
    dest: /home/jogi/.zsh-plugins/

- name: download zsh-syntax-highlighting plugin
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /home/jogi/.zsh-plugins/

- name: create .zshrc from template
  template:
    src: /templates/.zshrc
    dest: /home/jogi/.zshrc

- name: source .zshrc
  command: 'source /home/jogi/.zshrc'