- name: install zsh
  package:
    name: zsh
    state: latest

- name: create zsh-themes directory
  file:
    path: /home/jogi/.zsh-themes
    state: directory

- name: create gnzh directory inside .zsh-themes
  file:
    path: /home/jogi/.zsh-themes/gnzh
    state: directory

- name: download gnzh theme
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/themes/gnzh.zsh-theme
    dest: /home/jogi/.zsh-themes/gnzh/


- name: create zsh-plugins directory
  file:
    path: /home/jogi/.zsh-plugins
    state: directory

- name: create zsh-autosuggestions directory
  file:
    path: /home/jogi/.zsh-plugins/zsh-autosuggestions/
    state: directory

- name: download zsh autosuggestions plugin
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: /home/jogi/.zsh-plugins/zsh-autosuggestions

- name: create zsh-completion directory
  file:
    path: /home/jogi/.zsh-plugins/zsh-completions/
    state: directory

- name: download zsh completion plugin
  git:
    repo: https://github.com/zsh-users/zsh-completions.git
    dest: /home/jogi/.zsh-plugins/zsh-completions/

- name: create zsh-syntax-hightlighting directory
  file:
    path: /home/jogi/.zsh-plugins/zsh-syntax-hightlighting
    state: directory

- name: download zsh-syntax-highlighting plugin
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /home/jogi/.zsh-plugins/zsh-syntax-highlighting

- name: create .zshrc from template
  template:
    src: /templates/.zshrc
    dest: /home/jogi/.zshrc

- name: change ownership of created files and directories to jogi
  file:
    path: '{{ item }}'
    owner: jogi
    group: jogi
    mode: '0755'
    state: directory
    recurse: yes
  with_items:
    - /home/jogi/.zshrc/
    - /home/jogi/.zsh-plugins/
    - /home/jogi/.zsh-themes/

- name: source .zshrc
  command: 'source /home/jogi/.zshrc'