- name: add jogi to wheel group
  user:
    name: jogi
    groups: wheel
    append: true

- name: allow wheel group to use sudo
  lineinfile:
    path: /etc/sudoers
    regexp: '^(.*)%wheel ALL=(ALL) ALL(.*)$'
    line: '%wheel ALL=(ALL) ALL'
    state: present
