- name: install mysql
  package:
    name: mysql-server
    state: latest

- name: install pip3
  package:
    name: python3-pip
    state: latest

- name: install PyMySQL
  pip:
    name: PyMySQL

- name: start mysql
  systemd:
    name: mysql
    state: started

- name: enable mysql
  systemd:
    name: mysql
    state: enabled

- name: Change the authentication plugin of MySQL root user to mysql_native_password
  command: mysql -u root -e 'UPDATE mysql.user SET plugin="mysql_native_password" WHERE user="root" AND host="localhost"'

- name: Flush Privileges
  command: mysql -u root -e 'FLUSH PRIVILEGES'

- name: mysql_secure_installation
  mysql_secure_installation:
    login_user: root
    login_password: {{ mysql_root_password }}
    disable_remote_root_login: true
    remove_anonymous_user: true
    remove_test_db: true
    reload_privilege_table: true

- name: create nextcloud database
  mysql_db:
    login_user: root
    login_password: '{{ mysql_root_password }}'
    name: nextcloud
    state: present
