- name: install nextcloud from snap
  snap:
    name: nextcloud
    state: present

- name: allow port 80
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: allow port 443
  ufw:
    rule: allow
    port: 443
    proto: tcp
