- name: install nextcloud from snap
  snap:
    name: nextcloud
    state: present

#- name: setup nextcloud admin account
#  command: nextcloud.manual-install {{ nextcloud_admin_username }} {{ nextcloud_admin_password }}

- name: adjust nextcloud trusted domains
  command: nextcloud.occ config:system:set trusted_domains 1 --value={{ nextcloud_domain_name }}

- name: allow port 80
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: allow port 443
  ufw:
    rule: allow
    port: 443
    proto: tcp

#- name: obtain ssl certificate
#  command: nextcloud.enable-https lets-encrypt
