- include_tasks: unattended_upgrades.yml
  when: ansible_os_family == 'Debian'

- include_tasks: zfs_installation.yml
  when: is_nas_server is defined and is_nas_server == true

- include_tasks: nas_server_setup.yml
  when: is_nas_server is defined and is_nas_server == true

- include_tasks: static_ip.yml
  when: static_ip is defined

- include_tasks: install_syncthing.yml
  when: is_syncthing_server is defined and is_syncthing_server == true

- include_tasks: install_plex_server.yml
  when: is_plex_server is defined and is_plex_server == true
