- name: include server tasks
  include_tasks: "{{ item }}"
  loop:
    #- nextcloud_installation/mysql_setup.yml
    #- nextcloud_installation/apache_and_php_setup.yml
    #- auto_updates.yml
    #- nfs_server_setup.yml
