- name: include unattended upgrades
  include_tasks: unattended_upgrades.yml
  when: ansible_os_family == 'Debian'

- name: include nextcloud installation
  include_tasks: nextcloud_snap_installation/nextcloud_snap_installation.yml
  when: instance_type is defined and instance_type == 'nextcloud'
