- name: install nfs server package
  package:
    name: nfs-kernel-server
    state: latest

- name: change nfs/rpc to use static port for mountd
  lineinfile:
    path: /etc/default/nfs-kernel-server
    regexp: '^(.*)RPCMOUNTDOPTS(.*)$'
    line: 'RPCMOUNTDOPTS="--port 33333"'
    firstmatch: true

- name: copy exports to /etc/exports
  template:
    src: exports
    dest: /etc/exports

- name: reload nfs exports
  command: exportfs -a

- name: restart nfs server service
  systemd:
    name: nfs-kernel-server
    state: restarted

- name: install samba
  package:
    name: samba
    state: latest

- name: add block to config file
  blockinfile:
    path: /etc/samba/smb.conf
    block: |
      [public]
         path = /pool/data/family/public
         browsable = yes
         read only = no
         guest ok = yes
      
      [johannes]
         path = /pool/data/johannes
         browsable = yes
         read only = no
         guest ok = no
         vaild users = jogi
      
      [dirk]
         path = /pool/data/family/dirk
         browsable = yes
         read only = no
         guest ok = no
         vaild users = dirk
      
      [christine]
         path = /pool/data/family/christine
         browsable = yes
         read only = no
         guest ok = no
         vaild users = christine
      
      [konstantin]
         path = /pool/data/family/konstantin
         browsable = yes
         read only = no
         guest ok = no
         vaild users = konstantin
      
      [charlotte]
         path = /pool/data/family/charlotte
         browsable = yes
         read only = no
         guest ok = no
         vaild users = charlotte

- debug:
    msg: Now run 'sudo useradd <username> && sudo smbpasswd -a <username>' to add samba users

- debug:
    msg: Then restart smbd server

- debug:
    msg: Also change login shell for the new users to /usr/sbin/nologin

- debug:
    msg: When mounting an external ext2/3/4 drive for storage keep in mind that 5% are reserved for the root user! To change this, run "tune2fs -m 0 <drive>"
