- name: install mysql and apache2 (apt install mysql-server, apache2)
  package:
    name:
      - mysql-server
      - apache2
    state: latest

- name: adds python mysql support (apt install python-mysqldb)
  package:
    name: python-mysqldb
    state: latest

- name: set root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host: localhost

- name: Removes server anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: set root access to localhost only
  mysql_user:
    login_host: localhost
    login_user: root
    login_password: ''
    name: root
    password: "{{ mysql_root_password }}"
    state: present
    host: ['127.0.0.1', '::1', 'localhost']

- name: remove test databse
  mysql_user:
    login_host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"
    db: test
    state: absent


- name: create nextcloud database (mysql; CREAT DATABASE nextcloud)
  mysql_db:
    name: nextcloud
    state: present

- name: grant privileges to nextcloud database (GRANT ALL PRIVILEGES ON nextcloud.* TO 'nextcloud'@'localhost IDENTIFIED BY 'password')
  command: mysql -u root -e "GRANT ALL PRIVILEGES ON nextcloud.* TO 'nextcloud'@'localhost IDENTIFIED BY '{{ mysql_root_password }}'"

- name: install required php packages (apt install <package>)
  package:
    - php
    - php-apcu
    - php-bcmath
    - php-cli
    - php-common
    - php-curl
    - php-gd
    - php-gmp
    - php-imagick
    - php-intl
    - php-mbstring
    - php-mysql
    - php-zip
    - php-xml

- name: enable php mods (phpenmod bcmath gmp imagick intl)
  command: phpenmod bcmath gmp imagick intl

- name: download nextcloud from source and put it into /var/www/ directory (wget nextcloud-<version>.zip)
  get_url: https://download.nextcloud.com/server/releases/nextcloud-21.0.0.zip
    dst: /var/www/

- name: unzip nextcloud download (unzip /var/www/nextcloud-<version>.zip -d /var/www/)
  unarchive:
    src: /var/www/nextcloud-21.0.0.zip
    dst: /var/www/

- name: rename nextcloud folder (mv /var/www/nextcloud /var/www/<site>)
  command: mv /var/www/nextcloud /var/www/nc.test.de

- name: disable apache default website (a2dissite 000-default.conf)
  command: a2dissite 000-default.conf

- name: create apache config file for nextcloud test_site
  template:
    src: nc.test.de.conf
    dst: /etc/apache2/sites-available/nc.test.de.conf

- name: enable newly created config file (a2ensite <site>)
  command: a2ensite nc.test.de

- name: enable required apache mods (a2enmod dir env headers mime rewrite ssl)
  command: a2enmod dir env headers mime rewrite ssl

- name: restart apache service to apply changes (systemctl restart apache2)
  systemd:
    name: apache2
    state: restarted

- name: correct permissions of php config file (chmod 660 /var/www/<site>/config/config.php; chown root:www-data /var/www/<site>/config/config.php)
  file:
    path: /var/www/nc.test.de/config/config.php
    owner: root
    group: www-data
    mode: 0660

- name: add certboot repo (add-apt-repository ppa:certbot/certbot)
  command: add-apt-repository ppa:certbot/certbot

- name: create ssl sertificate (certbot --apache -d <site>)
  command: certbot --apache -d <site>
