- name: copy netplan config from template
  template:
    src: netplan/00-installer-config.yaml.j2
    dest: /etc/netplan/00-installer-config.yaml

- name: apply netplan configuration
  command: netplan apply