- name: install unattended-upgrades
  package:
    name: unattended-upgrades
    state: latest

- name: copy 20-auto-upgrades config file
  template:
    src: unattended_upgrades/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades

- name: copy 50unattended-upgrades config file
  template:
    src: unattended_upgrades/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
