---

- name: install basic packages
  package:
    - openssh-server
    - rsync
    - bash-completion
    - curl
    - wget
    - vim
    - nano
    - git
    - htop
    - python3
    - python3-pip
    - cron
    state: latest