- name: install base packages
  package:
    name: '{{ item }}'
    state: latest
  loop:
    - rsync
    - wget
    - curl
    - bash-completion
    - nano
    - git
    - htop
    - unzip
    - tar
    - ethtool
    - lshw
    - man
