- name: install base packages
  package:
    name: {{ item }}
    state: latest
  loop:
    - openssh
    - ethtool
    - rsync
    - wget
    - curl
    - bash-completions
    - vim
    - nano
    - git
    - htop
    - lshw