- name: install base packages
  package:
    name: '{{ item }}'
    state: latest
  loop:
    - rsync
    - wget
    - curl
    - bash-completion
    - nano
    - git
    - htop
    - unzip
    - tar
    - man-db

- name: install python and pip package on Arch-based systems
  package:
    name: '{{ item }}'
    state: latest
  loop:
    - python
    - python-pip
  when: ansible_os_family == 'Archlinux'

- name: install python and pip package on Debian-based systems
  package:
    name: '{{ item }}'
    state: latest
  loop:
    - python3
    - python3-pip
  when: ansible_os_family == 'Debian'
