- name: install base packages
  package:
    name: '{{ item }}'
    state: latest
  loop:
    - ethtool
    - rsync
    - wget
    - curl
    - bash-completion
    - vim
    - nano
    - git
    - htop
    - lshw