- name: create openssh keypair locally named as the server
  become_user: jogi
  openssh_keypair:
    path: /home/jogi/.ssh/{{ ansible_nodename }}
  delegate_to: 127.0.0.1

- name: copy newly created public key to the server
  authorized_key:
    user: jogi
    state: present
    key: "{{ lookup('file', '/home/jogi/.ssh/{{ ansible_nodename }}.pub') }}"

- name: add host to ~/.ssh/config file locally so the private key doensne't need to specified every time
  become_user: jogi
  blockinfile:
    path: /home/jogi/.ssh/config
    block: |
      Host {{ ansible_default_ipv4['address'] }}
       HostName {{ ansible_default_ipv4['address'] }}
       User jogi
       IdentityFile ~/.ssh/{{ ansible_nodename }}
  delegate_to: 127.0.0.1
