- name: include base tasks
  include_tasks: "{{ item }}"
  loop:
    #- update_linux.yml
    #- setup_ufw.yml
    #- setup_ssh.yml
    #- exchange_ssh_keys.yml
    #- base_packages.yml
    #- language_setup.yml