- name: install ufw (apt/pacman/dnf install/-S/install openssh)
  package:
    update_cache: true
    name: ufw
    state: latest

- name: deny server incoming traffic (ufw default deny incoming)
  ufw:
    default: deny
    direction: incoming

- name: allow server outgoing traffic (ufw default allow outgoing)
  ufw:
   default: allow
   direction: outgoing

- name: limit port 22 for ssh connections (ufw limit 22)
  ufw:
    rule: limit
    port : '22'
    proto: tcp

- name: enable ufw (ufw enable)
  ufw:
    state: enabled
