- name: install ufw
  package:
    update_cache: true
    name: ufw
    state: latest

- name: deny incoming traffic
  ufw:
    default: deny
    direction: incoming

- name: allow outgoing traffic
  ufw:
   default: allow
   direction: outgoing

- name: enable ufw
  ufw:
    state: enabled
