- name: install ufw
  package:
    update_cache: true
    name: ufw
    state: latest

- name: deny server incoming traffic
  ufw:
    default: deny
    direction: incoming

- name: allow server outgoing traffic
  ufw:
   default: allow
   direction: outgoing

- name: limit port 22 for ssh connections
  ufw:
    rule: limit
    port : '22'
    proto: tcp

- name: enable ufw
  ufw:
    enabled: true
