- name: install ssh
  package:
    name: '{{ ssh_package }}'
    state: latest

- name: start and enable openssh
  systemd:
    name: sshd
    state: started
    enabled: true

- name: disable root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^(.*)PermitRootLogin(.*)$'
    line: 'PermitRootLogin no'
    firstmatch: true

- name: disable password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^(.*)PasswordAuthentication(.*)$'
    line: 'PasswordAuthentication no'
    firstmatch: true

- name: restart ssh service to apply changes
  systemd:
    name: sshd
    state: restarted