- name: install ufw
  package:
    update_cache: true
    name: ufw
    state: latest

- name: deny incoming traffic
  ufw:
    default: deny
    direction: incoming

- name: allow outgoing traffic
  ufw:
   default: allow
   direction: outgoing

- name: limit port 22 from LAN if it doesn't need to be accessed from the Internet
  ufw:
    rule: limit
    port: 22
    proto: tcp
    src: '{{ ansible_default_ipv4["network"] }}/24'
  when: internet_facing is defined and internet_facing == false

- name: limit port 22 from anywhere if it needs to be accessed from the Internet
  ufw:
    rule: limit
    port: 22
    proto: tcp
  when: internet_facing is defined and internet_facing == true

- name: enable ufw
  ufw:
    state: enabled

- name: enable ufw service since it is disabled on arch-based distros by default
  systemd:
    name: ufw
    enabled: true
