- name: install ufw
  package:
    update_cache: true
    name: ufw
    state: latest

- name: deny incoming traffic
  ufw:
    default: deny
    direction: incoming

- name: allow outgoing traffic
  ufw:
   default: allow
   direction: outgoing

- name: limit port 22
  ufw:
    rule: limit
    port: 22
    proto: tcp
    src: 192.168.178.0/24

- name: allow port 80 if it's a web server
  ufw:
    rule: allow
    port: 80
    proto: tcp
  when: webserver is defined and webserver == true

- name: allow port 443 if it's a web server
  ufw:
    rule: allow
    port: 443
    proto: tcp
  when: webserver is defined and webserver == true

- name: enable ufw
  ufw:
    state: enabled

- name: enable ufw service since it is disabled on arch-based distros by default
  systemd:
    name: ufw
    enabled: true
