- name: install ufw
  package:
    update_cache: true
    name: ufw
    state: latest

- name: deny incoming traffic
  ufw:
    default: deny
    direction: incoming

- name: allow outgoing traffic
  ufw:
   default: allow
   direction: outgoing

- name: limit port 22 if it is a ssh server
  ufw:
    rule: limit
    port: 22
    proto: tcp
  when: is_ssh_server is defined and is_ssh_server == true

- name: allow port 53 for DNS requests if it is a DNS server
  ufw:
    rule: allow
    port: 53
    proto: any
  when: is_dns_server is defined and is_dns_server == true

- name: allow port 80 if it is a web server
  ufw:
    rule: allow
    port: 80
    proto: tcp
  when: is_http_server is defined and is_http_server == true

- name: allow port 443 if it is a web server
  ufw:
    rule: allow
    port: 443
    proto: tcp
  when: is_https_server is defined and is_https_server == true

- name: enable ufw
  ufw:
    state: enabled

- name: enable ufw service since it is disabled on arch-based distros by default
  systemd:
    name: ufw
    enabled: true
