- name: update Arch-based systems
  pacman:
    update_cache: true
    upgrade: true
  when: ansible_os_family == 'Archlinux'
  register: updated

- name: udpate Debian-based systems
  apt:
    update_cache: true
    upgrade: true
  when: ansible_os_family == 'Debian'
  register: updated

- name: udpate RedHat-based systems
  yum:
    update_cache: true
    name: '*'
    state: latest
  when: ansible_os_family == 'RedHat'
  register: updated

- name: reboot host to apply updates (If kernel is updated and the system is not rebooted, there are conflicts with ufw/iptables later on)
  reboot:
  when: updated.changed
