---

- hosts: all
  become: true
  tasks:

  - name: update arch systems, equivalent to 'pacman -Syu'
    pacman:
      update_cache: true
      upgrade: true
    when: ansible_distribution == 'Archlinux'
