---

- hosts: all
  become: true
  tasks:

  - name: update Arch-based systems, equivalent to 'pacman -Syu'
    pacman:
      update_cache: true
      upgrade: true
    when: ansible_os_family == 'Archlinux'

  - name: udpate Debian-based systems, equivalent to 'apt update; apt upgrade'
    apt:
      update_cache: true
      upgrade: true
    when: ansible_os_family == 'Debian'

  - name: udpate RedHat-based systems, equivalent to 'dnf update; dnf upgrade'
    yum:
      update_cache: true
      name: '*'
      state: latest
    when: ansible_os_family == 'RedHat'